use core::fmt::{Display, Formatter, Result as FmtResult};

#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub enum Note {
    CMinus2,
    CSharpMinus2,
    DMinus2,
    DSharpMinus2,
    EMinus2,
    FMinus2,
    FSharpMinus2,
    GMinus2,
    GSharpMinus2,
    AMinus2,
    ASharpMinus2,
    BMinus2,
    CMinus1,
    CSharpMinus1,
    DMinus1,
    DSharpMinus1,
    EMinus1,
    FMinus1,
    FSharpMinus1,
    GMinus1,
    GSharpMinus1,
    AMinus1,
    ASharpMinus1,
    BMinus1,
    C0,
    CSharp0,
    D0,
    DSharp0,
    E0,
    F0,
    FSharp0,
    G0,
    GSharp0,
    A0,
    ASharp0,
    B0,
    C1,
    CSharp1,
    D1,
    DSharp1,
    E1,
    F1,
    FSharp1,
    G1,
    GSharp1,
    A1,
    ASharp1,
    B1,
    C2,
    CSharp2,
    D2,
    DSharp2,
    E2,
    F2,
    FSharp2,
    G2,
    GSharp2,
    A2,
    ASharp2,
    B2,
    #[default]
    C3,
    CSharp3,
    D3,
    DSharp3,
    E3,
    F3,
    FSharp3,
    G3,
    GSharp3,
    A3,
    ASharp3,
    B3,
    C4,
    CSharp4,
    D4,
    DSharp4,
    E4,
    F4,
    FSharp4,
    G4,
    GSharp4,
    A4,
    ASharp4,
    B4,
    C5,
    CSharp5,
    D5,
    DSharp5,
    E5,
    F5,
    FSharp5,
    G5,
    GSharp5,
    A5,
    ASharp5,
    B5,
    C6,
    CSharp6,
    D6,
    DSharp6,
    E6,
    F6,
    FSharp6,
    G6,
    GSharp6,
    A6,
    ASharp6,
    B6,
    C7,
    CSharp7,
    D7,
    DSharp7,
    E7,
    F7,
    FSharp7,
    G7,
    GSharp7,
    A7,
    ASharp7,
    B7,
    C8,
    CSharp8,
    D8,
    DSharp8,
    E8,
    F8,
    G8,
}

impl TryFrom<u8> for Note {
    type Error = ();

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Note::CMinus2),
            1 => Ok(Note::CSharpMinus2),
            2 => Ok(Note::DMinus2),
            3 => Ok(Note::DSharpMinus2),
            4 => Ok(Note::EMinus2),
            5 => Ok(Note::FMinus2),
            6 => Ok(Note::FSharpMinus2),
            7 => Ok(Note::GMinus2),
            8 => Ok(Note::GSharpMinus2),
            9 => Ok(Note::AMinus2),
            10 => Ok(Note::ASharpMinus2),
            11 => Ok(Note::BMinus2),
            12 => Ok(Note::CMinus1),
            13 => Ok(Note::CSharpMinus1),
            14 => Ok(Note::DMinus1),
            15 => Ok(Note::DSharpMinus1),
            16 => Ok(Note::EMinus1),
            17 => Ok(Note::FMinus1),
            18 => Ok(Note::FSharpMinus1),
            19 => Ok(Note::GMinus1),
            20 => Ok(Note::GSharpMinus1),
            21 => Ok(Note::AMinus1),
            22 => Ok(Note::ASharpMinus1),
            23 => Ok(Note::BMinus1),
            24 => Ok(Note::C0),
            25 => Ok(Note::CSharp0),
            26 => Ok(Note::D0),
            27 => Ok(Note::DSharp0),
            28 => Ok(Note::E0),
            29 => Ok(Note::F0),
            30 => Ok(Note::FSharp0),
            31 => Ok(Note::G0),
            32 => Ok(Note::GSharp0),
            33 => Ok(Note::A0),
            34 => Ok(Note::ASharp0),
            35 => Ok(Note::B0),
            36 => Ok(Note::C1),
            37 => Ok(Note::CSharp1),
            38 => Ok(Note::D1),
            39 => Ok(Note::DSharp1),
            40 => Ok(Note::E1),
            41 => Ok(Note::F1),
            42 => Ok(Note::FSharp1),
            43 => Ok(Note::G1),
            44 => Ok(Note::GSharp1),
            45 => Ok(Note::A1),
            46 => Ok(Note::ASharp1),
            47 => Ok(Note::B1),
            48 => Ok(Note::C2),
            49 => Ok(Note::CSharp2),
            50 => Ok(Note::D2),
            51 => Ok(Note::DSharp2),
            52 => Ok(Note::E2),
            53 => Ok(Note::F2),
            54 => Ok(Note::FSharp2),
            55 => Ok(Note::G2),
            56 => Ok(Note::GSharp2),
            57 => Ok(Note::A2),
            58 => Ok(Note::ASharp2),
            59 => Ok(Note::B2),
            60 => Ok(Note::C3),
            61 => Ok(Note::CSharp3),
            62 => Ok(Note::D3),
            63 => Ok(Note::DSharp3),
            64 => Ok(Note::E3),
            65 => Ok(Note::F3),
            66 => Ok(Note::FSharp3),
            67 => Ok(Note::G3),
            68 => Ok(Note::GSharp3),
            69 => Ok(Note::A3),
            70 => Ok(Note::ASharp3),
            71 => Ok(Note::B3),
            72 => Ok(Note::C4),
            73 => Ok(Note::CSharp4),
            74 => Ok(Note::D4),
            75 => Ok(Note::DSharp4),
            76 => Ok(Note::E4),
            77 => Ok(Note::F4),
            78 => Ok(Note::FSharp4),
            79 => Ok(Note::G4),
            80 => Ok(Note::GSharp4),
            81 => Ok(Note::A4),
            82 => Ok(Note::ASharp4),
            83 => Ok(Note::B4),
            84 => Ok(Note::C5),
            85 => Ok(Note::CSharp5),
            86 => Ok(Note::D5),
            87 => Ok(Note::DSharp5),
            88 => Ok(Note::E5),
            89 => Ok(Note::F5),
            90 => Ok(Note::FSharp5),
            91 => Ok(Note::G5),
            92 => Ok(Note::GSharp5),
            93 => Ok(Note::A5),
            94 => Ok(Note::ASharp5),
            95 => Ok(Note::B5),
            96 => Ok(Note::C6),
            97 => Ok(Note::CSharp6),
            98 => Ok(Note::D6),
            99 => Ok(Note::DSharp6),
            100 => Ok(Note::E6),
            101 => Ok(Note::F6),
            102 => Ok(Note::FSharp6),
            103 => Ok(Note::G6),
            104 => Ok(Note::GSharp6),
            105 => Ok(Note::A6),
            106 => Ok(Note::ASharp6),
            107 => Ok(Note::B6),
            108 => Ok(Note::C7),
            109 => Ok(Note::CSharp7),
            110 => Ok(Note::D7),
            111 => Ok(Note::DSharp7),
            112 => Ok(Note::E7),
            113 => Ok(Note::F7),
            114 => Ok(Note::FSharp7),
            115 => Ok(Note::G7),
            116 => Ok(Note::GSharp7),
            117 => Ok(Note::A7),
            118 => Ok(Note::ASharp7),
            119 => Ok(Note::B7),
            120 => Ok(Note::C8),
            121 => Ok(Note::CSharp8),
            122 => Ok(Note::D8),
            123 => Ok(Note::DSharp8),
            124 => Ok(Note::E8),
            125 => Ok(Note::F8),
            126 => Ok(Note::G8),
            _ => Err(()),
        }
    }
}

impl Display for Note {
    fn fmt(&self, f: &mut Formatter) -> FmtResult {
        // TODO TryFrom
        write!(
            f,
            "{}",
            match *self {
                Note::CMinus2 => "C-2",
                Note::CSharpMinus2 => "C#-2",
                Note::DMinus2 => "D-2",
                Note::DSharpMinus2 => "D#-2",
                Note::EMinus2 => "E-2",
                Note::FMinus2 => "F-2",
                Note::FSharpMinus2 => "F#-2",
                Note::GMinus2 => "G-2",
                Note::GSharpMinus2 => "G#-2",
                Note::AMinus2 => "A-2",
                Note::ASharpMinus2 => "A#-2",
                Note::BMinus2 => "B-2",
                Note::CMinus1 => "C-1",
                Note::CSharpMinus1 => "C#-1",
                Note::DMinus1 => "D-1",
                Note::DSharpMinus1 => "D#-1",
                Note::EMinus1 => "E-1",
                Note::FMinus1 => "F-1",
                Note::FSharpMinus1 => "F#-1",
                Note::GMinus1 => "G-1",
                Note::GSharpMinus1 => "G#-1",
                Note::AMinus1 => "A-1",
                Note::ASharpMinus1 => "A#-1",
                Note::BMinus1 => "B-1",
                Note::C0 => "C0",
                Note::CSharp0 => "C#0",
                Note::D0 => "D0",
                Note::DSharp0 => "D#0",
                Note::E0 => "E0",
                Note::F0 => "F0",
                Note::FSharp0 => "F#0",
                Note::G0 => "G0",
                Note::GSharp0 => "G#0",
                Note::A0 => "A0",
                Note::ASharp0 => "A#0",
                Note::B0 => "B0",
                Note::C1 => "C1",
                Note::CSharp1 => "C#1",
                Note::D1 => "D1",
                Note::DSharp1 => "D#1",
                Note::E1 => "E1",
                Note::F1 => "F1",
                Note::FSharp1 => "F#1",
                Note::G1 => "G1",
                Note::GSharp1 => "G#1",
                Note::A1 => "A1",
                Note::ASharp1 => "A#1",
                Note::B1 => "B1",
                Note::C2 => "C2",
                Note::CSharp2 => "C#2",
                Note::D2 => "D2",
                Note::DSharp2 => "D#2",
                Note::E2 => "E2",
                Note::F2 => "F2",
                Note::FSharp2 => "F#2",
                Note::G2 => "G2",
                Note::GSharp2 => "G#2",
                Note::A2 => "A2",
                Note::ASharp2 => "A#2",
                Note::B2 => "B2",
                Note::C3 => "C3",
                Note::CSharp3 => "C#3",
                Note::D3 => "D3",
                Note::DSharp3 => "D#3",
                Note::E3 => "E3",
                Note::F3 => "F3",
                Note::FSharp3 => "F#3",
                Note::G3 => "G3",
                Note::GSharp3 => "G#3",
                Note::A3 => "A3",
                Note::ASharp3 => "A#3",
                Note::B3 => "B3",
                Note::C4 => "C4",
                Note::CSharp4 => "C#4",
                Note::D4 => "D4",
                Note::DSharp4 => "D#4",
                Note::E4 => "E4",
                Note::F4 => "F4",
                Note::FSharp4 => "F#4",
                Note::G4 => "G4",
                Note::GSharp4 => "G#4",
                Note::A4 => "A4",
                Note::ASharp4 => "A#4",
                Note::B4 => "B4",
                Note::C5 => "C5",
                Note::CSharp5 => "C#5",
                Note::D5 => "D5",
                Note::DSharp5 => "D#5",
                Note::E5 => "E5",
                Note::F5 => "F5",
                Note::FSharp5 => "F#5",
                Note::G5 => "G5",
                Note::GSharp5 => "G#5",
                Note::A5 => "A5",
                Note::ASharp5 => "A#5",
                Note::B5 => "B5",
                Note::C6 => "C6",
                Note::CSharp6 => "C#6",
                Note::D6 => "D6",
                Note::DSharp6 => "D#6",
                Note::E6 => "E6",
                Note::F6 => "F6",
                Note::FSharp6 => "F#6",
                Note::G6 => "G6",
                Note::GSharp6 => "G#6",
                Note::A6 => "A6",
                Note::ASharp6 => "A#6",
                Note::B6 => "B6",
                Note::C7 => "C7",
                Note::CSharp7 => "C#7",
                Note::D7 => "D7",
                Note::DSharp7 => "D#7",
                Note::E7 => "E7",
                Note::F7 => "F7",
                Note::FSharp7 => "F#7",
                Note::G7 => "G7",
                Note::GSharp7 => "G#7",
                Note::A7 => "A7",
                Note::ASharp7 => "A#7",
                Note::B7 => "B7",
                Note::C8 => "C8",
                Note::CSharp8 => "C#8",
                Note::D8 => "D8",
                Note::DSharp8 => "D#8",
                Note::E8 => "E8",
                Note::F8 => "F8",
                Note::G8 => "G8",
            }
        )
    }
}
